package com.l1337.l467;


import java.util.HashSet;
import java.util.Set;

public class Solution {

    //TLE O(p.length()^2)
    public int findSubstringInWraproundString(String p) {
        if (p.length() <= 1)
            return p.length();

        boolean [] dp = new boolean[p.length()];
        Set<Character> set = new HashSet<>(); // you just need denote the first ch
        int total = 0;

        //init for dp
        for (int i = 0; i < p.length(); ++i) {
            char c = p.charAt(i);
            if (!set.contains(p.charAt(i))) {
                set.add(c);
            }
            dp[i] = true;
        }
        total += set.size();
        set.clear();

        for (int l = 2; l <= p.length(); ++l) {
            for (int i = 0; i + l - 1 < p.length(); ++i) {
                char lastChar = p.charAt(i + l - 1);
                if (dp[i]) {
                    char startChar = p.charAt(i);
                    dp[i] = (((lastChar - 'a' + 1) % 26) == ((startChar - 'a' + l) % 26));
                    if (dp[i] && !set.contains(startChar))
                        set.add(startChar);
                } else {
                    //keep dp[i] as false unchanged.
                }
            }

            total += set.size();
            //opt for early termination
            if (set.size() == 0)
                break;
            set.clear();
        }

        return total;
    }

//    https://leetcode.com/problems/unique-substrings-in-wraparound-string/discuss/95439/concise-java-solution-using-dp/
    public static void main(String [] args) {
        Solution s = new Solution();
        System.out.println(s.findSubstringInWraproundString("bcdefghijklmnopqrstuvwcdefghijklmnopqrstuijklmnopqrstuvbcdefghijklmnopqrstustuvwnopqrstuvwxdefghcdefghijklmnopqrscdefghijklmnopqrstopqrstuijklmklmnhijklmnopqrstuvwxyzdetuqrsabcdefghijklmnopqrstghijklmnopqrpqmnoklmnopefghifghijklmnopqrstuvbcdklmnopjkuvwxytuvwxyzqrstdefgabcdefghcdefghijklmklmnoklmnopqrstuvwxabcdefghijklmnopqrstuvwxyzuvabcdefghijkbcdefghijklmnopqrstuvwxstuvwpqrrsthijklmnopqrstuvwxyzcdefghijklmnopqrstuvwxyzhijklmnopqrshijklmnopqrshijklmnopuvhijklmnbcdefghijklmnopuvwxylmnopqrstuvwxyzcdefghijklmnopqrvwxbcdefghijklmnopqrstuvwnopqvghijklmnopqrstucdefabcdefghijklmnopqrstlmnopbcdeabcdefghijklmnqrstuvwxyzpqrcdefghiabcdefghijkjklmnopqbcdefghijklmnopefghbcdefghijkdefghijklmnopqrstupqrstuvwxyzmnopqrstuvwxyzdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvhijklmnopqrstuvyzopqrstbcdstuvwxybcdefghijknoghijklmnstuvdefghiabcdefghijklmnopqrstuvwxyijklmnopqrstuvwxywxyzhijklbcdefghiabcdefghimnhijklmnopqrstmnopqrststuvwhijklmnofghijklmnopqrstuvwxpqrghijklmnopqrbcdefghijklmnopqrstuvwxyzijklmnqrbcdefghijklmnjklmnopbcdefghijghijkmdefghijklmnopqrstuvwxhijklmnophijklmnopqrsqrstuvwxhijklmnopqqrsnodefghijklmnobcdefghabcdefghijklmhijklmnopqrqrstuvwxyzghijklmnhijklmnopqrsqrstuvwxnopqrstuvwdefghijklmnopqrstuuvwxyghijklmnopqrijklmnopqcdefghmnopqrstuvwxyhijkcdefghijklabcdefghijklmnhijklmnopqrstuvwxyghijkcdefcdefgjklmnopqrsefghijklmnopqrstuvbcdefghijklmnopqrstuvwxopqrstuvwxyzklmnopqrbcdefabcdefgghijklmnklmnqrsfghijklmnopqrstuvlmnopqpqrstulmnopqrefghijklmnopqrstuvfghijklmnoghijklmhijklmnvwabcdeabcdefghijklmnopqrsdefghijklmnopdefghicdefghijklmnopqhijklmnoklmnopopqrsthijklmnopqrabcdefghijklmnopqrstuvwxyqrstuvwopghijklmnopqrijdghijklmnopqrscdefghijklmhijklmnopqrstuvmnopqrstulmtuhijklmnopklmnopqrstvwxyjklmnfghijklmmnrstklmnvwxcdefghghijklmnopqrstuvlmnopqrstijklmnopqrstuvwxyzdefghijkvwxyopqrstuvabcdefghijklmpopqrstuvwxdefghijklmnopqrshijklmnopqrstuvwxycdfghijklmnopqrstuvwxyefgpqrstuvdefghijkghijklmnofgklmnopqrstjklmqrstuvwxyzefghijklmnopqrstuvwcdefghijklmnofghijklmnghfghijklmpefghijkljklmnopqrstefghijklmnopqrstuijklmnopqrstuvwxyzefbcdersdefghhklmnopqrstuvwxyfghijklmnopqrnopqrsklmnijklmnopqrstuvwxyijklhnopqrstuvwxmnoklmnopjklmnopqcdefgklmnopqrjklmnopqrsttijklmnopqrstuvwxhijklmdefghijklmnopefghijklmnopqrstuvwxabcdefghnopdefghijklmnopqrstuvrstuvwxyzbcdefghibcdfghijklopqrstuvwxyzijklmnopqrstefghijklmnopopqrstuvwxmnorstefghijklmnopqrstuvwxyijklmnopqrstuvbcdefghijklmnopqrstupqrstuvwxyghijklmnopqrstuvbcdefghijklmnopqrstuvwxyzcdefghijklmnopqrstustuvwxhabcdefghijklmnopmlmnopqrstijklabcdeffghijkfqdefghqrstuvwxytuvwxyvwxyklmnopqrstuvwnopqrstuvghijklmnopwxdefghijklmnopqrstfghijklmnopqrstuvwxjkldefghijklrstefghijklmnopqrstuvwabcdefghijklmnfghijqrststuvwghijklmnopqrstuvwxyefghijkdefghijklmnopqrstuklmnopqrstuvijklmnopqefhijklmnopflmnopqrstcdefghijklmnopqrstuvwxwxyzcdefdefghijklmnopqrstjklmnopqrstuvdefghijklmnopqrstuvwxhijklmnopqrstuvwxyzdefghijklmnopqrsrdefghijkabcdefghijabcdefghijklmnopqrstuvwxyzklmnopqrstudefghijklmnnopqrstuvwxynopqrstbcdefghijklmhijklmabcdefghijklmnopqrstuvwxybcdefghijklmnfghijklmnoqrijklmnopopqklmnojklmnefghijklmnopqrstuklmnopabcdefghijklmwxybcdefghijklmnabcdefopdefghijklmefghijklmnopqrstudefghijkfbcdefghijbcdefghijkbcdefghijklmnopqlmnopqrstuvwxyfghijklmnopqrstuvwxyzmnopqrstuvwxyjklmnopqrstuvdefghijklmnopqrstuvuvwnopqfghiklmnopqbcdefghijklmnopqghijpqrstudefghijklmnopqrstujklmnopqrstuvwabcdefghijklmnijklmnopqhijklmnopqrstuvwklmnopqrstucdefghifghbcdefghihijklpqstuvwxbcdefghijklmnopqrstuvwxyzdefghijkcdefghijklmlmnopqrstuvwxyzvwxyzcdefghijklmefghijklmnopqrghijklmnopqrstuvefghijklmnohijklmnopqrstuabcdefghijmnopabcdefghijklmnopqrstuvwxyzhijklmnopqrstucdefghidefghijklmnopqrstuvwxyznopqrstfghimnopqrstmnopqklmnopqrsmnopqrstuklmnopqrstuvwxyzdnopqrstuvrsrstuvwxabcdtbcdefgdefghijklmnopqrstuefghijklmnopqrslmghijklmnopqrsklmnopklmnopqrstuabcdcdefghijklmnolmnopqrstuvwxyznopqrstuvwxybcdefghijklmnopqrstufefghijklmnostuvwxyzabcdefghijklmnpqrstuvwvfgefghijklmnopopqrstuvyzbcdefghijklmnopqrstuvwxyzcdefghijuvqrstuvklmnopqrstuvwxiefghijklopqrshijklmnoefghijklmnopqstuvbcdefghibcdefghijklmnopqrstuefghijklmnopqrstuvwdefghijkbcdefghijklmnopqrstudefghijklghijklmnopqrlmnopqrstghijklmnopqghijklmnopqrsijklmnopqrstulmnopcdefghijkdefghijklmnopqrstuvwxyhijklmnopqghijklmnopqbcdefghijklmnfghijklmnopqrstuvwxbcdeflmnopqrstuvwnopqrfghijklmnopabcdefghirstopqrsmnopqrsnopobcdefghijklmnopqrstuvwxbcdefghijklmnopqrstuvwbcdefgefghijklmnopqrklmnopqabcdefghijklmnopqrstubcdefghijklbcdefghiabcdepqrstufgcdefghijklmnopqrstuvwxyzrstuvwjklmghijklmnopqrstuvwrstuvwefghijklmnopqrstuvwxyfghijklmnopqrstuvijklmnopqrstuvwjklmnopqghijklmnjklmnoprsvwxyzijklmnopqrstuvwbcdefghijklmnbcdefghijklmndefghijklmnabcdefghijklmnopxyefghijklmnopqrstuabcdefghijklmabcdefghijklmnopqrstuvwdefghijvwfghifghijklmabcdefghijklmnopdefghijklmnopqrstuvwxyrdefghijklmndefghabcdefghijklmnoprstuvwfghijklmnmnohijklmnopqrscdefghiopqrstuvwlmndefghijklmnopqrstuvwqrstuvtklmopqhijklmnoyfghijktuvwxygtuvwxyznopqrhijklmnopqrstuvwxyzbcdefghiabcdefijklmnopqrstefghijklmnopqrstuijklmnopqrstijklmnopqrstuvwxyopqrstuvwxydefgfghijklmnopqrstuvcdebcdefghijklmnopqrsbdejklmnopxyopqrstuvwxyzfghijklmnopqrsabcdefghijklmnopbcdefghijklmnjklmnopqrstuvwxnopqrstuvwxydefghijklmnopqrstuuvwxyzuvwxyzrstuvwstuvwxyzdefghijklmnopqrstuvwxyzefghijklmnopqrstuvefghijklmnopqrstuvjklmnopqrstuvwxycdefghijklmnopqrstuvwxhijklijklmnopqrstuvwxyefghijklmnoptklmnopqrsghijhijklmnopqrstabcdefghijklmnopqghijklmnopqrsijklmnopqrstuvwxyzmnopqrlmnopqrsghijkrstvwxydefghijklmnopqrstuvwghijklmnopqruvwxbcdefghijklmnfghijklmnklmnopqropqrstudcdefghijklmnocdefghijklmnopqrstdefghijklqabcdefghifghijklmnopqrstuvwxyzstuvwxpqrstuvwxnopqrstuvwxdefghijkcdefghijstuvwxlmnoabcdefghijklmnopqrsnodefghijklmnopqrabopqrklmnopghijklcdebcdefghijklmnopqrstujklmnopqrstuvwxyzhijklmnopqrstuvbcdefghbcdefghijklmnopqrstuvwxyzopqrstuvwxyzijklmnopghijkcdefghfghicdefghijklefghijklcdefghijklmdefghijklmnopklmnopqrfghijklmcdefghijklmnopqrstuvwxymnopqrrstuvwxyzbcdefghijklcdbcdefghijklmnopqrstuvwhijklmnonopklmnopqrstuvwstcdefgtuvwxcdcdefghijklmnopqrstuvpopqruvwxyznopqrstuvwxydefghijklibcdefghijklmnostuijklmnonopqrshijklmnopqrswxyzvqrstlmnopqrstuvwxyzhijklmnopqrbcdefghijklmnoefghijklmnopqrstabcdefghijkdefghijklmnopqefghijklmnopqrstufghpqrstuvmnopqrhijklmnopqrstuvklmdefefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwxyzefghijklmnopqrstuvwxyzjklcdefghijklmnopqrstuvwxhcdefghijkqrstcdefghijklmnocdefabcdrstughijklmnopqrstuvwxcdefghijklmnopqrstghijklmnopqrstuvwxyzzmnopqrsthijklmnopqrstutuvjklhijklmnopqrsbcdefghijklmnopqrstuvwxjklmghijklmnopqrstqrstuijklmnopqrstfghijklmnopqrstuvnodefghijklmnopqrstuvwxydefghijklmnopqrstuabcdeopqrbcdefghiijklmnopbcdefghijklmfghijklmnopqrstrstuvijklmnopqrstuvwxyzwxyrshijklmnopqrstuklmnopqabcdefghijklmbcdefghijklmnopqrstuvwxyabcdefghiabclmnopqrstuvwxydefghijklmnopqstuhijklmnopqlmnopcdefghijklmnohijklmnopqrstudefghijklmnopqrstuvdefghijklmnopqrabcdefghijkpqrstuvwxrstfghijklbcdefghicdefthijklmnorstqrstuvwxbcdefghijklmnopqfghijklmnopqmncdefghijklmnopqrstuvwxyzcdefghijklmnopqrstuhijklmnopqrstuvwjklmnopqrstefghijklmnopqrsbcdefghijklmnopqrstuvwxqrstuvabcdefghijklmnopqrstuvwcdefghijklmnopqrslmnopqrspqrqrstuvwxyzklrstghijklmnodefghijlmnopqrstuvwxklmnostuvghijklmnopghijklmnopqrstnopqrstuvwxyzstabcdefgcdefgefghijklmnopqrstuvwxyznopqrstuvwxyzklmnopqrstuvwxyzuvdefghijklmnopqrstuvefghijklmnopqrstmnopqrstuvwghijklmnrstutuvwxdefghijklmnopabcdefopqrslmijkabghijklmnopqrstuvwxstjklmnopcdefghijklmnopqrstuvwxyzefghijklmopqrstuvwxstuvopqrslmnopqrstuvwmnopqrsjklmnopqrstuvwdefghijklmnopqrstuvwxyklmnopqrstuvwabcdefghijklmnopqrstuvwxyklmnopqrstuvwxyghijklmnefghijklmnopqrefghijkjklmnopqrcdfghijefghijhijklmnopqrstuvwxyzmnopqrqrstuvwcdefghijklmnopqrzpqrstuvwxybchijklmnopqrabcdefghicdefghijklmnopmnojkijklmnopqrsdefghijklmnopqrstuvwsghijklmnopqrstuvcdeflmnopqrstucdefghijklmnopqrstuvwxcdefghijklmnopqrstuvwxdefghijklmnopqrstuvwxrstuvwxymnopqrstuvwxyzijklmnopqrsijkjklmnopqrswxyzabcklmnnfghijklmnopqrstuvwxhijklmnopqrstuvwxyklmnoghijkdefghijklabcdefghijklmnopbcdefghijklmnopqrstuvwxyjklmnopqwxjklmnopqrstmnopqrstuvabcdefghijklmnopqrstuvwxyzijknoefefuvwxefghijklmnopqrstuvwxyzdefghijklmnopqrstjklmnopqrstuvwhijklmnopqrstuvwxyztuvhijklmnoabcdefghijklmnopqrstuvwijklmnopqrstuvwxdefghijklmnopqrstuvwbcdefghijklmfghijklmnopqrsijklmnopqrbcdefghijklmnopqrstuvwxopqrstuhijklmnopqrstuvwxyzdebcdefghibcdefghijklmnopqrsfghijklmnopqghijklmnopqrsdefghijklmnopqrstuvwjklmnopqrstuvwxyzghijklmnopqrstuvwjklmnopqrbcdefghijklmnopqmnopqrstuvwxyzdefghijklmqrstbcdefghijklmnopqrstuvwxdefghijklmnabcdefpqrstuvwxopqrstuvrstlmnxymnopqrsjklmnopqrstughijlmnopghijklmnopqrstuvwxklmnopqrstuvwxdefghijklmnopqtuvwxyuvwcdefghijklmnopqrstuvwxyzhijklmnopqrbcdefghijklmijklmnopqrstuvabcdefghijklmnopqrstuvwxyabcdefghighijklmnopqrstfghijklcdefghijkllfghijkmnopqrstunopqrstuvwxyznopqdefghijklcdefghijklmnopqrstuvwxyghijklmbcdefghijkzcdefghijklmnopvwhijklmnuvwxyznopqrstuvwxyzijklmnopqrsbcdefghijklmnopqrstuvwxyzghijklmnopqrsabcdefghijklmnopqpqrstuvwefghijklmnocdefghijklmnoopqrsbcdefghijklmnopqrshicdefghijklmnopqrstuvwxopqrstuvwxyzdefgvwdbsefghijklmnopqrjklmnopqrsijklmabcmnopqbcdefghijklmnbcdefghijklmnoopqrstuvwxijklmnopqrstuvwxyopqrstuvwxyzefghijklmnopqrstuvwxjklmnoklmnopqrstuvwmnopqrsrstucdefghijklmnopqrstfghijklmnopqrjklcdefghijklstuvwxyfghijklmnopqrjklmabcdefghijklmnopqrstughijklmnopqrstuvwxyzqrstuvlmnopqrstuvwxyzghijklmnojklfghijkghijklmnopqrstabcdefghijkghijklmnopqrstuefghijklmnopqrabcdefghijklmfghijklmnopqrstuvwxyefghijklmnopqrscdefghijklmnopqrstfghijklmnopqrstrstujklmnopqrsdefghdefghijklmnabcdefghijklmnouvwxyzghijklmnopqrcdefghijklmnopqrstuvwjklmnopqbcdefghijklmnopqklmnopqrstulmnopqrstuvwxyzabcdefghijklmnoefghijklmnopqrstuvwxyfghbcdefghijklmnopqrdefghijklmnopqrstuvwxyzijklmnopqrstabcdeffghijklmnopqrstuvwxklmnopqrstuefghijklmnopqrstdefghijklmnopqrstuv"));
    }
}
